manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zuanming
      url-base: https://github.com/zuanming
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-oled-adapter
      remote: zuanming
      revision: main
    - name: zmk-nice-oled
      remote: zuanming
      revision: main
    - name: zmk-dongle
      remote: zuanming
      revision: main
    - name: zmk-dongle-display
      remote: zuanming
      revision: main  
    - name: nice-view-battery                
      remote: zuanming                       
      revision: main   
  self:
    path: config
